### ISSUE TITLE
GRES not supported in new slurm version 20.11

### ISSUE THREAD

**Issue by antoniomarcum** [NordicHPC/slurm2sql#7]
I received the error 'slurm acct: GRES deprecated' after slurm was updated to version 20.11
Slurm deprecated the use of GRES in the [recent release notes](https://slurm.schedmd.com/news.html).

> COMMAND CHANGES (see man pages for details)
>  -- sacct - AllocGres and ReqGres were removed. Alloc/ReqTres should be used
>     instead.

I edited the main script and replaced the some lines with gres for tres and the string search from gpu: to gpu=

``` python
# GPU stuff
class slurmReqGPU(linefunc):
    @staticmethod
    def calc(row):
        tres = row['ReqTRES']
        if not tres:  return None
        m = re.search(r'gpu=(\d+)', tres)
        if m:
            return int(m.group(1))
```

**Comment by rkdarst** [comment]
Thanks for making this issue!  It is always good to catch these things early. I just made a update in pull request #9, which should fix this for newer Slurm without breaking it for older Slurm.  But, since I don't have a newer slurm I can't test myself.

- This uses what you have found, but I don't know if there are other considerations to be aware of
- This adds a new column no the database ReqTRES.  So, old databases and new can't be updated in-place, but we never promised that so hopefully it is OK.

Can you give it a try and see if it works?  If you need help let me know.  (I might leave that pull request open for a bit to see if anyone finds other bugs in it).

**Comment by antoniomarcum** [comment]
Yes, seems to be working well for me! Thanks!
